// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pearson
Rcpp::List pearson(const Rcpp::NumericVector& useFlag, const Rcpp::NumericVector& precisionFlag, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& y);
RcppExport SEXP gputools_pearson(SEXP useFlagSEXP, SEXP precisionFlagSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type useFlag(useFlagSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type precisionFlag(precisionFlagSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(pearson(useFlag, precisionFlag, x, y));
    return rcpp_result_gen;
END_RCPP
}
// kendall
Rcpp::NumericMatrix kendall(const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& y, const Rcpp::NumericVector& precisionFlag);
RcppExport SEXP gputools_kendall(SEXP xSEXP, SEXP ySEXP, SEXP precisionFlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type precisionFlag(precisionFlagSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall(x, y, precisionFlag));
    return rcpp_result_gen;
END_RCPP
}
